services:
  logic_structure_llm:
    build: ./
    tty: true
    container_name: logic_structure_llm
    volumes:
      - .:/usr/src/code
    working_dir: /usr/src/code/
    ports:
      - "11434:11434"
    network_mode: host
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"