instance_dir: data/instances/blocksworld/generated_basic_3
generalized_instance_dir: blocksworld/generated
domain_file: data/pddlgenerators/blocksworld/4ops/domain.pddl
prompt_json_file: "data/prompts/blocksworld_3/task_1_plan_generation.json"
domain_name: blocksworld
engine: BlocksworldChat
n_instances: 501
start: 1
end: 500
instances_template: instance-{}.pddl
few_shot: 2
domain_intro: |
   I am playing with a set of blocks where I need to arrange the blocks into stacks. Here are the actions I can do

   Pick up a block
   Unstack a block from on top of another block
   Put down a block
   Stack a block on top of another block

   I have the following restrictions on my actions:
   I can only pick up or unstack one block at a time.
   I can only pick up or unstack a block if my hand is empty.
   I can only pick up a block if the block is on the table and the block is clear. A block is clear if the block has no other blocks on top of it and if the block is not picked up.
   I can only unstack a block from on top of another block if the block I am unstacking was really on top of the other block.
   I can only unstack a block from on top of another block if the block I am unstacking is clear.
   Once I pick up or unstack a block, I am holding the block.
   I can only put down a block that I am holding.
   I can only stack a block on top of another block if I am holding the block being stacked.
   I can only stack a block on top of another block if the block onto which I am stacking the block is clear.
   Once I put down or stack a block, my hand becomes empty.
   Once you stack a block on top of a second block, the second block is no longer clear.

few_shot_example_1: |
   [STATEMENT]
   As current conditions I have that, the blue block is clear, the orange block is clear, the hand is empty, the blue block is on top of the red block, the red block is on the table and the orange block is on the table.
   My goal is to have that the red block is on top of the blue block and the orange block is on top of the red block.

   Return the first action I need to take to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the orange block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   put down the orange block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the blue block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   unstack the blue block from on top of the red block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   put down the blue block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the red block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the blue block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   unstack the orange block from on top of the red block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   stack the red block on top of the blue block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the orange block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   stack the orange block on top of the red block

few_shot_example_2: |
   [STATEMENT]
   As current conditions I have that, the orange block is clear, the hand is empty, the blue block is on top of the red block, the orange block is on top of the blue block and the red block is on the table.
   My goal is to have that the red block is on top of the blue block and the orange block is on top of the red block.

   Return the first action I need to take to achieve my goal. Return one, and only one, action, without nothing more.
   unstack the orange block from on top of the red block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   unstack the orange block from on top of the blue block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   put down the orange block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   unstack the blue block from on top of the red block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   put down the red block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   put down the orange block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   unstack the blue block from on top of the red block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   unstack the red block from on top of the blue block
   human: This action is not possible due to the set of restrictions. Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.
   put down the blue block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the red block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   stack the red block on top of the blue block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   pick up the orange block
   human: Good action! Return the next action to achieve my goal. Return one, and only one, action, without nothing more.
   stack the orange block on top of the red block

prompts:
   feedback_prompts:
         positive: "Good action! "
         negative: "This action is not possible due to the set of restrictions. "
   order_prompts: 
         positive: "Return the next action to achieve my goal. Return one, and only one, action, without nothing more.\n"
         negative: "Return one action that is allowed by the set of restrictions. Return one, and only one, action, without nothing more.\n"
         first_prompt: "Return the first action I need to take to achieve my goal. Return one, and only one, action, without nothing more.\n"

actions:
  {pickup: "pick up the {}",
   putdown: "put down the {}",
   stack: "stack the {} on top of the {}",
   unstack: "unstack the {} from on top of the {}"}


predicates:
  {ontable: "the {} is on the table",
   clear: "the {} is clear",
   handempty: "the hand is empty",
   holding: "the hand is currently holding {}",
   "on": "the {} is on top of the {}"}

predicate_mapping:
   {
   "ontable": "on the table",
   "clear": "clear",
   "handempty": "hand is empty",
   "holding": "holding",
   "on": "on top of"
   }  


# encoded_objects: dictionary of object names, have to be alphabetical
encoded_objects:
  {"a": "red block", "b": "blue block", "c": "orange block", "d": "yellow block",
   "e": "white block", "f": "magenta block", "g": "black block", "h": "cyan block",
   "i": "green block", "j": "violet block", "k": "silver block", "l": "gold block" }

callbacks:
   - t1_gen_goal_directed_instances