task_config: configs/blocksworld_chat_with_possible_actions_feedback.yaml
instance_id: 874
max_iterations: 10
max_iterations_prompt_iterative: 5
instance_range: [2, 102]
blocksworld: generated_basic
temperature: 0
one_shot: False
model: mixtral
#model: llama2:70b
#model: mistral
#model: llama2:13b-chat
#model: gpt-4-0125-preview
run_single: False
json_output_dir: experiments_results
dataset_folder: dataset/blocksworld/blocksworld_2000_4_blocks_balanced
sample_rate: 1
seed: 42