task_config: configs/blocksworld_chat.yaml
instance_id: 2
max_iterations: 10
model: llama2:70b
#model: mistral
#model: llama2:13b-chat
#model: gpt-4-0125-preview
run_single: True
json_output: experiments_results/test.json