instance_id: 2
blocksworld: generated_basic
json_output_dir: experiments_results
results_folder: experiments_results/paper/cot_validation_llama
dataset_folder: dataset/blocksworld/blocksworld_2000_4_blocks_balanced
domain_file: data/pddlgenerators/blocksworld/4ops/domain.pddl
model_name: Mixtral
seed: 42

actions:
  {pickup: "pick up {}",
   putdown: "put down {}",
   stack: "stack {} on top of {}",
   unstack: "unstack {} from on top of {}"}


predicates:
  {ontable: "the {} is on the table",
   clear: "the {} is clear",
   handempty: "the hand is empty",
   holding: "the hand is currently holding {}",
   "on": "the {} is on top of the {}"}

predicate_mapping:
   {
   "ontable": "on the table",
   "clear": "clear",
   "handempty": "hand is empty",
   "holding": "holding",
   "on": "on top of"
   }  


# encoded_objects: dictionary of object names, have to be alphabetical
encoded_objects:
  {"a": "red block", "b": "blue block", "c": "orange block", "d": "yellow block",
   "e": "white block", "f": "magenta block", "g": "black block", "h": "cyan block",
   "i": "green block", "j": "violet block", "k": "silver block", "l": "gold block" }